# Generated by Django 5.2.3 on 2025-06-16 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('design', 'Design'), ('other', 'Other')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('document_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('metrka', 'Birth Certificate')], max_length=10, null=True)),
                ('document_series', models.CharField(blank=True, max_length=30, null=True)),
                ('jshshir', models.CharField(blank=True, max_length=20, null=True)),
                ('document_given_by', models.CharField(blank=True, max_length=255, null=True)),
                ('document_given_date', models.DateField(blank=True, null=True)),
                ('parent_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_document_series', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_jshshir', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_document_given_by', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_document_given_date', models.DateField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
