# Generated by Django 5.2.3 on 2025-06-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
