# Generated by Django 5.2.3 on 2025-07-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
