# Generated by Django 5.2.3 on 2025-07-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='phone',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
