# Generated by Django 5.2.3 on 2025-06-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
