# Generated by Django 5.2.3 on 2025-07-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contract_initial_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='monthly_price',
            new_name='monthly_duration',
        ),
    ]
