# Generated by Django 5.2.3 on 2025-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_contract_contract_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
